apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingressroutes
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/base/ingressroutes
  prune: true
  wait: true
  timeout: 5m0s