apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      # The Pod anti-affinity rule tells the scheduler to avoid placing multiple app=http-server servers on a single node
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - http-server
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: http-server-ruby
        image: ghcr.io/hpc-student/http_server:main-553de53a4a939008d97366495a6095812edb9eef-9 # {"$imagepolicy": "flux-system:http-server"}
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "100Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 2
        ports:
        - containerPort: 80
