apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
        app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server-ruby
        image: ghcr.io/hpc-student/http_server:main-382d55097a70f85b5c2af54227bcf54eea3e4b06-5 # {"$imagepolicy": "flux-system:http-server"}
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "100Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 2
        ports:
        - containerPort: 80

