---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: http-server
  namespace: default
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: http-server
  targetCPUUtilizationPercentage: 50

