apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: http-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: http-server
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>[1-9][0-9]*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc