apiVersion: v1
kind: Service
metadata:
  name: http-server
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
